table Clientes

	column id_cliente
		dataType: string
		summarizeBy: none
		sourceColumn: id_cliente

	column canal_principal
		dataType: string
		summarizeBy: none
		sourceColumn: canal_principal

	column ops
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: ops

	column dias_activos
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: dias_activos

	column simbolos
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: simbolos

	column monto_ars
		dataType: double
		formatString: #,##0
		summarizeBy: none
		sourceColumn: monto_ars

	column ops_ene
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ops_ene

	column ops_feb
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ops_feb

	column ops_mar
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ops_mar

	column score_riesgo
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: score_riesgo

	column nivel_riesgo
		dataType: string
		summarizeBy: none
		sourceColumn: nivel_riesgo
		sortByColumn: orden_nivel

	column orden_nivel
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: orden_nivel

	column motivos
		dataType: string
		summarizeBy: none
		sourceColumn: motivos

	column p1_actividad_alta
		dataType: boolean
		summarizeBy: none
		sourceColumn: p1_actividad_alta

	column p2_horario_atipico
		dataType: boolean
		summarizeBy: none
		sourceColumn: p2_horario_atipico

	column p3_cambio_brusco
		dataType: boolean
		summarizeBy: none
		sourceColumn: p3_cambio_brusco

	column p3_sin_historial_monto_alto
		dataType: boolean
		summarizeBy: none
		sourceColumn: p3_sin_historial_monto_alto

	column p4_precio_fuera_mercado
		dataType: boolean
		summarizeBy: none
		sourceColumn: p4_precio_fuera_mercado

	column diferencia_valor_ars
		dataType: double
		formatString: #,##0
		summarizeBy: none
		sourceColumn: diferencia_valor_ars

	column log10_ops
		dataType: double
		formatString: 0.00
		summarizeBy: sum
		sourceColumn: log10_ops

	column log10_monto_ars
		dataType: double
		formatString: 0.00
		summarizeBy: sum
		sourceColumn: log10_monto_ars

	column rank_monto
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: rank_monto

	column rank_ops
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: rank_ops

	partition Clientes = m
		mode: import
		source =
				let
					Origen = Csv.Document(File.Contents(CarpetaDatos & "clientes.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
					Tipos = Table.TransformColumnTypes(Encabezados, {{"id_cliente", type text}, {"canal_principal", type text}, {"ops", Int64.Type}, {"dias_activos", Int64.Type}, {"simbolos", Int64.Type}, {"monto_ars", type number}, {"ops_ene", Int64.Type}, {"ops_feb", Int64.Type}, {"ops_mar", Int64.Type}, {"score_riesgo", Int64.Type}, {"nivel_riesgo", type text}, {"orden_nivel", Int64.Type}, {"motivos", type text}, {"diferencia_valor_ars", type number}, {"log10_ops", type number}, {"log10_monto_ars", type number}, {"rank_monto", Int64.Type}, {"rank_ops", Int64.Type}}, "en-US"),
					Booleanos = Table.TransformColumns(Tipos, {{"p1_actividad_alta", each _ = "t", type logical}, {"p2_horario_atipico", each _ = "t", type logical}, {"p3_cambio_brusco", each _ = "t", type logical}, {"p3_sin_historial_monto_alto", each _ = "t", type logical}, {"p4_precio_fuera_mercado", each _ = "t", type logical}})
				in
					Booleanos

